python:
  - "2.7"

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi --force-yes
  # Print versions we use
  - arm-none-eabi-gcc --version
  - python --version

install:
  - sudo pip install mbed-cli

env:
  - TARGET=NUCLEO_F411RE
  - TOOLCHAIN=GCC_ARM

script:
  - mbed deploy
  - mbed compile --library --target ${TARGET} --toolchain ${TOOLCHAIN}
